dataset:
  repo_id: repo_dp
  root: Datasets/example/top_long_merged
  image_transforms:
    # Linked to --dataset.image_transforms.enable in run_2run_dino_sweep.sh
    enable: false

policy:
  type: dino_diffusion
  vision_backbone: facebook/dinov2-small
  spatial_pooling: baseline
  use_registers: false
  num_register_tokens: 4
  map_num_queries: 8
  device: cuda
  push_to_hub: false
  use_amp: false

  crop_shape: null
  crop_is_random: false

  input_features:
    observation.state:
      type: STATE
      shape: [12]
    observation.images.top_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.left_rgb:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.right_rgb:
      type: VISUAL
      shape: [3, 480, 640]

  output_features:
    action:
      type: ACTION
      shape: [12]

output_dir: outputs/sweep_10k/DINOv2_Baseline
job_name: DINOv2_Baseline
batch_size: 8
steps: 10000
save_freq: 10000
log_freq: 500

wandb:
  enable: true
  project: lehome_challenge
